In [14]:
import pandas as pd

# Sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob'],
        'Subject': ['Math', 'Science', 'Math', 'Science', 'Math'],
        'Score': [80, 75, 85, 90, 88]}

df = pd.DataFrame(data)

df.groupby(['Name','Subject']).mean()

Score
Name    Subject       
Alice   Math      80.0
        Science   90.0
Bob     Math      88.0
        Science   75.0
Charlie Math      85.0

In [19]:
# Custom function to calculate the range
def score_range(x):
    return x.max() - x.min()

# Applying custom aggregation function
result = grouped['Score'].agg(score_range)

print(result)


Name     Subject
Alice    Math       0
         Science    0
Bob      Math       0
         Science    0
Charlie  Math       0
Name: Score, dtype: int64


In [16]:
grouped

In [27]:
for name,group in grouped:
    #print(name,group)
    print(group['Name'][0])
    break

Alice


In [28]:
df['mean_score'] = grouped['Score'].transform('mean')

In [29]:
df

Name  Subject  Score  mean_score
0    Alice     Math     80        80.0
1      Bob  Science     75        75.0
2  Charlie     Math     85        85.0
3    Alice  Science     90        90.0
4      Bob     Math     88        88.0

In [30]:
df['mean_score_2'] = df['Score'].apply(lambda x : x.mean())
df

AttributeError: 'int' object has no attribute 'mean'

In [33]:
grouped.filter(lambda x : x['Score'].mean()  > 80)

Name  Subject  Score  mean_score
2  Charlie     Math     85        85.0
3    Alice  Science     90        90.0
4      Bob     Math     88        88.0

In [2]:
import numpy as np 

# Creating array object 
arr = np.array( [[ 1, 2, 3],
                 [ 1, 2, 3],
                 [ 1, 2, 3],
				[ 4, 2, 5]] ) 

# Printing type of arr object 
print("Array is of type: ", type(arr)) 

# Printing array dimensions (axes) 
print("No. of dimensions: ", arr.ndim) 

# Printing shape of array 
print("Shape of array: ", arr.shape) 

# Printing size (total number of elements) of array 
print("Size of array: ", arr.size) 

# Printing type of elements in array 
print("Array stores elements of type: ", arr.dtype) 


Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (4, 3)
Size of array:  12
Array stores elements of type:  int32


In [32]:
a = np.zeros(3,dtype='int')

In [38]:
np.full((2,3),fill_value=5)

array([[5, 5, 5],
       [5, 5, 5]])

In [71]:
a =np.random.random(5)
a

array([0.32407226, 0.6475658 , 0.44743425, 0.28082883, 0.25206043])

In [49]:
a[0].dtype

TypeError: 'int' object is not subscriptable

In [72]:
e = np.random.randint(1,5,100) 
e

array([2, 2, 3, 4, 2, 4, 2, 4, 1, 3, 2, 4, 4, 1, 3, 1, 3, 4, 2, 4, 1, 4,
       3, 3, 1, 4, 4, 1, 3, 4, 1, 2, 1, 4, 3, 1, 2, 1, 4, 1, 3, 1, 4, 2,
       2, 4, 1, 1, 3, 4, 2, 2, 3, 2, 4, 3, 3, 3, 2, 4, 3, 1, 4, 1, 3, 2,
       3, 2, 1, 4, 3, 4, 2, 3, 2, 3, 3, 2, 4, 2, 1, 3, 2, 3, 1, 3, 3, 1,
       1, 3, 2, 1, 1, 1, 4, 4, 1, 3, 2, 2])

In [75]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a = np.linspace(1,10,10)

In [84]:
np.random.randint(1,100,10)

array([ 2, 45, 15, 54, 59, 30, 89, 82, 90, 24])

In [92]:
np.random.rand(3,4)

array([[0.74377413, 0.47124484, 0.06534427, 0.39950639],
       [0.57860001, 0.21503443, 0.50620313, 0.04283558],
       [0.03923317, 0.50868469, 0.33621442, 0.99358458]])

In [93]:
np.random.randint(1,100,(2,3))

array([[23, 11, 96],
       [32,  5, 51]])

In [94]:
np.random.random((3,4))

array([[0.07920544, 0.14225312, 0.69002751, 0.29999482],
       [0.66709337, 0.55405567, 0.36402908, 0.51162352],
       [0.49454284, 0.54999526, 0.66294801, 0.6499438 ]])

In [112]:
np.random.choice([1, 2, 3, 4, 5,6],(2,3),replace=False)

array([[5, 4, 2],
       [6, 3, 1]])

In [115]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
np.random.shuffle(np.arange(1,11))

In [126]:
# Using range()
python_range = range(1, 10, 2)  # Generates range object
print(list[python_range])  # Output: range(1, 10, 2)

# Using np.arange()
numpy_arange = np.arange(1, 10, 2)  # Generates NumPy array
print(numpy_arange)  # Output: [1 3 5 7 9]


[1 3 5 7 9]


In [131]:
np.linspace(0,8,10)

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

In [132]:
arr = np.array([[1, 2, 3, 4],
               [7, 3, 3, 6],
               [9, 6, 2, 8]])

In [141]:
arr.reshape(2,2,3)

array([[[1, 2, 3],
        [4, 7, 3]],

       [[3, 6, 9],
        [6, 2, 8]]])

In [176]:
lst1 = np.array([1,2,3,4,5,6,7,8,9])
lst2 = np.array([6,4,8,9,2,7,4,10,7])


In [182]:
lst1 + lst2.tolist()

array([ 7,  6, 11, 13,  7, 13, 11, 18, 16])

In [179]:
lst1 - lst2

array([-5, -2, -5, -5,  3, -1,  3, -2,  2])

In [183]:
lst1 * lst2

array([ 6,  8, 24, 36, 10, 42, 28, 80, 63])

In [185]:
lst1  / lst2

array([0.16666667, 0.5       , 0.375     , 0.44444444, 2.5       ,
       0.85714286, 1.75      , 0.8       , 1.28571429])

In [186]:
lst = [1,2,3,4,5,6,7,8,9]

In [187]:
lst[0]

1

In [188]:
lst[2:5]

[3, 4, 5]

In [190]:
lst[::2]

[1, 3, 5, 7, 9]

In [191]:
lst.append(10)

In [194]:
lst.insert(11,-1)

In [201]:
lst.insert(0,99)

In [202]:
lst

[99, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, -1]

In [203]:
lst.pop()

-1

In [204]:
lst

[99, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [205]:
lst.remove(10)

In [206]:
lst

[99, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [207]:
lst.remove(99)

In [212]:
lst.append(2)

In [213]:
lst.index(9)

8

In [214]:
lst.count(2)

2

In [216]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 2]

In [218]:
print(2 in lst)

True


In [221]:
lst = lst + [99,88]

In [228]:
lst.append(2)

In [229]:
{i:lst.count(i) for i in lst}

{1: 1, 2: 3, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1, 99: 1, 88: 1}

In [233]:
lst = [1, 2, 3, 4, 5, 2, 3, 2, 4, 5]
lst.append(2)
lst.append(2)
lst.append(99)
lst.append(4)
# # Count the occurrences of a specific element
# count_2 = lst.count(2)
# print("Count of 2:", count_2)  # Output: Count of 2: 3

# # Count the occurrences of all unique elements
# unique_elements = set(lst)
# for element in unique_elements:
#     count = lst.count(element)
#     print(f"Count of {element}: {count}")


In [236]:
#lst = [1, 2, 3, 4, 5, 2, 3, 2, 4, 5]

# Create an empty dictionary to store the counts
count_dict = {}

# Count the occurrences of all unique elements
for element in lst:
    if element in count_dict:
        count_dict[element] += 1
    else:
        count_dict[element] = 1

print(count_dict)


{1: 1, 2: 5, 3: 2, 4: 3, 5: 2, 99: 1}


In [237]:
from collections import Counter

Counter(lst)

Counter({2: 5, 4: 3, 3: 2, 5: 2, 1: 1, 99: 1})